import prisma from '../utils/prisma.js';
import { asyncHandler } from '../utils/asyncHandler.js';
import { audit } from '../services/auditService.js';
const parseList = (q, allowed) => ({ skip: (Math.max(+q.page || 1, 1) - 1) * Math.min(Math.max(+q.limit || 12, 1), 100), take: Math.min(Math.max(+q.limit || 12, 1), 100), orderBy: { [allowed.includes(q.sortBy) ? q.sortBy : 'createdAt']: q.order === 'asc' ? 'asc' : 'desc' } });
export const listProjects = asyncHandler(async (req, res) => { const { search, status } = req.query; const validStatus = ['NOT_STARTED', 'IN_PROGRESS', 'COMPLETED'].includes(status) ? status : undefined; const where = { userId: req.userId, ...(validStatus ? { status: validStatus } : {}), ...(search ? { name: { contains: search, mode: 'insensitive' } } : {}) }; const args = parseList(req.query, ['createdAt', 'name', 'startDate', 'endDate']); const [items, total] = await prisma.$transaction([prisma.project.findMany({ where, ...args, include: { _count: { select: { tasks: true } } } }), prisma.project.count({ where })]); res.json({ items, total, page: +req.query.page || 1, limit: args.take }); });
export const getProject = asyncHandler(async (req, res) => { const item = await prisma.project.findFirst({ where: { id: req.params.id, userId: req.userId }, include: { _count: { select: { tasks: true } } } }); if (!item) return res.status(404).json({ message: 'Project not found' }); res.json(item); });
export const createProject = asyncHandler(async (req, res) => { const item = await prisma.project.create({ data: { ...req.body, userId: req.userId, startDate: req.body.startDate ? new Date(req.body.startDate) : null, endDate: req.body.endDate ? new Date(req.body.endDate) : null } }); await audit(req.userId, 'CREATE', 'PROJECT', item.id); res.status(201).json(item); });
export const updateProject = asyncHandler(async (req, res) => { const exists = await prisma.project.findFirst({ where: { id: req.params.id, userId: req.userId } }); if (!exists) return res.status(404).json({ message: 'Project not found' }); const item = await prisma.project.update({ where: { id: exists.id }, data: { ...req.body, startDate: req.body.startDate ? new Date(req.body.startDate) : null, endDate: req.body.endDate ? new Date(req.body.endDate) : null } }); await audit(req.userId, 'UPDATE', 'PROJECT', item.id); res.json(item); });
export const deleteProject = asyncHandler(async (req, res) => { const item = await prisma.project.findFirst({ where: { id: req.params.id, userId: req.userId } }); if (!item) return res.status(404).json({ message: 'Project not found' }); await prisma.project.delete({ where: { id: item.id } }); await audit(req.userId, 'DELETE', 'PROJECT', item.id); res.status(204).send(); });
